02 09 family name
jlandwehr-avarteq/ruby_introduction_course pull request #15
Opened 2016-09-26 09:27 UTC by jlandwehr-avarteq

In this exercise I display all family members in people#show. People are automatically associated by their last name and ordered in ASC. Furthermore, the person itself is excluded from the list.

Note: I implemented this functionality with a name scope but had to give person with as an argument, because I was not able to implement it with self. => Please show me how to do it during the review.

@arkanoryn

2016-09-26 14:02 UTC, arkanoryn commented on family/app/models/person.rb
> +  #.order('first_name 'ASC)
??

2016-09-26 14:03 UTC, arkanoryn commented on family/app/models/person.rb
> +  #scope :family_members, -> (last_name){ where(last_name: last_name).order('first_name asc') }
??

2016-09-26 14:07 UTC, arkanoryn commented on family/app/models/person.rb
> +  #searches for all family members, order is not necessary and only there  for exercise purposes
Wrong comment.
`Searches for all family members except the person send...`

2016-09-26 14:08 UTC, arkanoryn commented on family/app/models/person.rb
> +  has_one :address,              as: :owner,    dependent: :destroy
align everything or align nothing.

2016-09-26 14:09 UTC, arkanoryn commented on family/app/controllers/degrees_controller.rb
> +  before_action :set_degree, only: [:show, :edit, :update, :destroy]
you know how to use a better way for your Array.

2016-09-26 14:09 UTC, arkanoryn commented on family/app/controllers/degrees_controller.rb
> +
empty line?

2016-09-26 14:10 UTC, arkanoryn commented on family/app/controllers/degrees_controller.rb
> +
empty line?

2016-09-26 14:11 UTC, arkanoryn commented on family/app/controllers/people_controller.rb
>    before_action :set_person, only: [:show, :edit, :update, :destroy]
you know a better way to declare arrays.

2016-09-26 14:11 UTC, arkanoryn commented on family/app/controllers/people_controller.rb
> +  before_action :set_degrees, only: [:new, :edit, :create, :update]
idem

2016-09-26 14:11 UTC, arkanoryn commented on family/app/controllers/people_controller.rb
> +  before_action :select_possible_friends, only: [:edit, :update]
idem.

2016-09-26 14:11 UTC, arkanoryn commented on family/app/controllers/people_controller.rb
> +    #@family = Person.family_members(@person.last_name)
what is this comment for?

2016-09-26 14:12 UTC, arkanoryn commented on family/app/controllers/people_controller.rb
> +    set_person_friends_from_params
what?!

2016-09-26 14:20 UTC, arkanoryn commented on family/app/controllers/people_controller.rb
> +    @possible_friends = Person.all.to_a - @person.friends.to_a
could you not make `@possible_friends = Person.all.to_a - @person.friends.to_a - [@person]`?

2016-09-26 14:20 UTC, arkanoryn commented on family/app/controllers/schools_controller.rb
> +  before_action :set_school, only: [:show, :edit, :update, :destroy]
can do better

2016-09-26 14:23 UTC, arkanoryn commented on family/app/controllers/schools_controller.rb
> +    # Use callbacks to share common setup or constraints between actions.
space before/after private

2016-09-26 14:26 UTC, arkanoryn commented on family/app/models/degree.rb
> +  has_many :people_degrees ,                dependent: :destroy
alignment?

2016-09-26 14:27 UTC, arkanoryn commented on family/app/models/friendship.rb
> +    #Friendship.create(inverse_friendship)
??

2016-09-26 14:27 UTC, arkanoryn commented on family/app/models/school.rb
> +  has_many :school_degrees,    dependent: :destroy
??

2016-09-26 14:43 UTC, arkanoryn commented on family/app/models/school.rb
> +  validates :school_name, presence: true
??

2016-09-26 14:44 UTC, arkanoryn commented on family/app/views/degrees/show.html.erb
> +      <%= school.school_name %>
??

2016-09-26 14:49 UTC, arkanoryn requested changes
I gave you some changes to do.
Please, apply and merge on `master`.

2016-09-29 09:29 UTC, jlandwehr-avarteq commented
Merge done.

2016-09-29 09:29 UTC, closed without merging